server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://apptruistic:apptruist1c@ds247479.mlab.com:47479/apptruistic?retryWrites=false
apptruistic:
  volunteerRole: "ROLE_VOLUNTEER"
  individualRole: "ROLE_INDIVIDUAL"
  organizationRole: "ROLE_ORGANIZATION"
  message: "Welcome"
  urgentLimitInWeeks: 1
  jwtSecret: "SecretKey"
  jwtExpirationMs: 86400000