server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${PROD_MONGODB}
  mailsetting:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
apptruistic:
  volunteerRole: "ROLE_VOLUNTEER"
  individualRole: "ROLE_INDIVIDUAL"
  organizationRole: "ROLE_ORGANIZATION"
  message: "Welcome"
  urgentLimitInWeeks: 1
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000