server:
  port: 8080
spring:
  data:
    mongodb:
      database: apptruistic-dev
      uri: mongodb://apptruistic:apptruist1c@ds155218.mlab.com:55218/apptruistic-dev?retryWrites=false
  mailsetting:
    host: smtp.gmail.com
    port: 587
    username: apptruistic@gmail.com
    password: aPP2020Trui$tic
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
apptruistic:
  volunteerRole: "ROLE_VOLUNTEER"
  individualRole: "ROLE_INDIVIDUAL"
  organizationRole: "ROLE_ORGANIZATION"
  message: "Welcome"
  urgentLimitInWeeks: 1
  jwtSecret: "SecretKey"
  jwtExpirationMs: 86400000
  maxQueueLength: 3